### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [ilona1986/kinoZal#9]
1)
Внешний вид заполнителей не соответствует макету.
![image](https://user-images.githubusercontent.com/8464662/135743345-72211d4d-2480-48ad-84cb-9b2375a4485c.png)

2)
Разрывов полей при переносах быть не должно.
![image](https://user-images.githubusercontent.com/8464662/135743384-e678b339-ab60-47e3-9390-8c620fbc393a.png)

**Comment by ilona1986** [comment]
2. Пофиксили применением к соотвествующему классу свойства  white-space: nowrap;
![image](https://user-images.githubusercontent.com/52574833/135748084-010a3c70-e7ea-4c8d-9054-fe299247e4eb.jpg)

**Comment by VadimVit** [comment]
Исправили:
![Работа над ошибками](https://user-images.githubusercontent.com/85961686/135764583-799fc77f-a9bf-475e-802e-da04c620d5e2.jpg)
